### ISSUE TITLE
Tasks for milestone 2

### ISSUE THREAD

**Issue by lyiris22** [UBC-MDS/Crime_Data#14]
Here are some tasks from the discussion:

data cleaning:
- [x] Center map on continental 
- [x] Fix bad points (Cincinnati, DC)
- [x] Baltimore repeated

app UI:
- [x] Get rid of comma in year filter (not a big deal)
- [x] axis title, labels, legends
- [x] change total pop from line to bar

to deploy:
- [x] make "app" folder name longer, for example "crime-data-app"
- [x] make the R file name "app.R"
- [x] have the data in the same folder with app.R

repo structure:
- [x] maybe a new folder to hold all the images?
- [x] update README.md

**Comment by aylapear** [comment]
Completed the ticks items
