### ISSUE TITLE
To-Do for Milestone 3

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/Crime_Data#22]
- [x] Add default value for city - Iris
- [x] Remove city filter from map tab - Iris
- [x] Remove crime type filter from 'single city' tab - Iris
- [x] Better title - Iris/Ayla
- [x] Add description about app 
- [x] Make more clear the bar graph is population 
- [ ] Update year filter so it doesn't look like a range selector (should look like a single value selector) - Richie
- [ ] Make different crimes different color circles - Richie
- [x] Add to tooltip (at very least, have crime rate number in tooltip) - Richie
- [x] Better delineation of graph and table on 'Single CIty' tab
- [x] Change table to show all years
- [ ] Change map filter to be checkbox (size by combo of crimes) - Richie
- [x] Change line graph filter to be checkbox
- [x] Change click to hover - Richie

**Comment by rzitomer** [comment]
Closing this issue because we've done all we will d on ito. Doesn't look like theres a way to make the year slider look less like a range and still have it be a slider. We also didn't color different crimes different colors because we changed the filter so we could select multiple crimes at once.
