### ISSUE TITLE
To-Do Milestone 4

### ISSUE THREAD

**Issue by rzitomer** [UBC-MDS/Crime_Data#31]
- [x] Be able to hover over line chart and get tooltip (convert to plotly?)
- [x] Have line colors be consistent regardless of what you select
- [x] Fix layout of help tab
- [x] Improve map interactivity (make it smoother, call out this functionality, etc.)
- [x] Add helper text to map tab
- [x] Fix 'San Jose' table bug
